services:
  caddy:
    image: ghcr.io/caddybuilds/caddy-cloudflare:latest
    network_mode: host
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro,z
      - caddy_data:/data
      - caddy_config:/config
    env_file: .env
    restart: always

volumes:
  caddy_data:
  caddy_config:
