services:
  openclaw:
    build: .
    init: true
    ports:
      - "127.0.0.1:18789:18789"
      - "127.0.0.1:18790:18790"
      - "127.0.0.1:6080:6080"
    env_file: .env
    environment:
      - HOME=/home/node
    volumes:
      - openclaw_config:/home/node/.openclaw
      - openclaw_workspace:/home/node/.openclaw/workspace
    shm_size: 2g
    restart: always

volumes:
  openclaw_config:
  openclaw_workspace:
