services:
  openclaw:
    image: ghcr.io/openclaw/openclaw:latest
    init: true
    ports:
      - "127.0.0.1:18789:18789"
      - "127.0.0.1:18790:18790"
    env_file: .env
    environment:
      - HOME=/home/node
    volumes:
      - openclaw_config:/home/node/.openclaw
      - openclaw_workspace:/home/node/.openclaw/workspace
    command: ["node", "dist/index.js", "gateway", "--bind", "lan", "--port", "18789", "--allow-unconfigured"]
    restart: unless-stopped

volumes:
  openclaw_config:
  openclaw_workspace:
